### ISSUE TITLE
First BT sync

### ISSUE THREAD

**Issue by LionZXY** [Flipper-Zero/Flipper-Android-App#15]
implement BT first sync.
Prototype:

![image](https://user-images.githubusercontent.com/5871715/91345918-c9113b00-e7e8-11ea-9990-1f14166cfd71.png)

or

![image](https://user-images.githubusercontent.com/5871715/91345928-cf9fb280-e7e8-11ea-9eb2-88e7a191d4bd.png)

**Comment by LionZXY** [comment]
Wait Flipper BT prototype

**Comment by Ne1c** [comment]
Bluetooth protocol does it stuff for you or this diagram about custom session establishment?
Do you have any documentation about bluetooth api for Flipper?

**Comment by LionZXY** [comment]
BT already implemented
