### ISSUE TITLE
Create base CI/CD

### ISSUE THREAD

**Issue by LionZXY** [Flipper-Zero/Flipper-Android-App#16]
Implement with GitHub actions:

- [ ] Build APK and publish in GitHub releases
- [ ] Check idea codestyle with [idea-cli-inspector](https://github.com/bentolor/idea-cli-inspector) or [ktlint](https://github.com/pinterest/ktlint)
- [ ] Run unit test

**Comment by dylanmtaylor** [comment]
Looks like this may already be building the apk file, I'm guessing the goal would be to have it conditionally publish to releases on new tags?

**Comment by LionZXY** [comment]
Publish on all new commit in `master` branch

**Comment by rougsig** [comment]
https://github.com/pinterest/ktlint
https://github.com/detekt/detekt
