### ISSUE TITLE
Add label for github actions build status

### ISSUE THREAD

**Issue by LionZXY** [Flipper-Zero/Flipper-Android-App#22]
Add label in readme with github action build status.
Like this:
![image](https://user-images.githubusercontent.com/5871715/91349375-e1d01f80-e7ed-11ea-8660-0192d727a01a.png)

May be using this? https://github.com/CultureHQ/github-actions-badge

**Comment by Technically-Possible** [comment]
Resolved With PR
https://github.com/Flipper-Zero/Flipper-Android-App/pull/23
